### ISSUE TITLE
Missing glossary entries for Clear the Deck card

### ISSUE THREAD

**Issue by uzikus1** [Kollieflower/Artifact2#37]
Clear the Deck card has two keywords ("lethal to creeps", "lethal to heroes") that are not rendered correctly in the Card Viewer. Those keywords do not appear on hover and are wrapped in quotation marks instead. They render normally in the game. [In-game screenshot](https://i.imgur.com/QwvK0bT.png) and [Card Viewer entry](https://kollieflower.github.io/Artifact2/?id=10344_0&l=false).

**Comment by Kollieflower** [comment]
I've amended this now. It's still not exactly as it is in game, but Clear The Deck at least now has Lethal To Heroes and Lethal To Creeps tooltips.
