### ISSUE TITLE
Loyal Beast not searchable

### ISSUE THREAD

**Issue by Allestein** [Kollieflower/Artifact2#5]
^

**Comment by DMzda** [comment]
Terrapin Greatshell and Channeler too.

**Comment by up201306506** [comment]
Yeah uncollectible cards toggle is something that was thought of. You also can't see things like malchanted mango.

**Comment by Kollieflower** [comment]
This is by design, but I can see why people would want to see these without going through the other cards first (eg going to Beastmaster to get to Loyal Beast). I'll look into adding a toggle to show these types of cards.

**Comment by Kollieflower** [comment]
Added an "Uncollectable" filter which, when turned on, shows cards such as Loyal Beast, Eidolon, Courier and Destroyed from Within.
